### ISSUE TITLE
mix test はパスするが、mix test.watchがパスしなくなっている

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [data-maestro/smallex#24]
# リビジョン
https://github.com/piacerex/smallex/commit/2ccf39065347451ec2d9f47ba83f1d844c1adac5

# elixir -v
```
Erlang/OTP 23 [erts-11.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```

- macOS 10.15.7
- もしかすると環境依存で私のマシンだけで起きている現象かもしれません

# mix test.watch で失敗する箇所

```
  1) doctest Fl.split_csv!/4 (7) (FlDocTest)
     test/fl_doc_test.exs:3
     ** (File.Error) could not remove file "test/split_sample-0.csv": no such file or directory
     stacktrace:
       (elixir 1.11.2) lib/file.ex:1130: File.rm!/1
       (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
       (for doctest at) lib/fl.ex:198: (test)
```

```elixir
iex> [ "test/split_sample-0.csv", "test/split_sample-1.csv", "test/split_sample-2.csv" ] |> Enum.map( & File.rm!( &1 ) )
[ :ok, :ok, :ok ]
```

# 変更案
- 私だけではなくみなさん発生する現象であれば変更したほうがよいとおもいます
- `Fl.split_csv!` のテストから後始末は削除
- `test/test_helper.exs` にファイルが存在する場合のみ削除するように処理を追加

```elixir:test/test_helper.exs
ExUnit.after_suite(fn _ ->
  ["test/split_sample-0.csv", "test/split_sample-1.csv", "test/split_sample-2.csv"]
  |> Enum.filter(&File.exists?(&1))
  |> Enum.map(&File.rm!(&1))
end)
```

**Comment by TORIFUKUKaiou** [comment]
- ファイル書き出し系のテストは出力先は、System.tmp_dir!() で取得した( /tmp 等)ディレクトリに作成をして、作成しっぱなしで削除のことは気にしないでもよいかもしれません

**Comment by TORIFUKUKaiou** [comment]
![スクリーンショット 2021-03-13 13 04 14](https://user-images.githubusercontent.com/4215723/111018532-ae0cbe00-83fc-11eb-906d-15bdcff03eea.png)

**Comment by TORIFUKUKaiou** [comment]
`File.exists?/1` をいれた理由を補足しておきます。
テストの実行の仕方によってはファイルが作られない場合があるからです。
例 `mix test test/crypt_doc_test.exs`

**Comment by TORIFUKUKaiou** [comment]
- afbb723449c82f9bde16bf58ba8e787d39fc6334 では発生しなくなっている
- たまたま?
